// Evidence index — what we actually know about a candidate, per dimension.
//
// The keystone for candidate analysis and comparison. Today the comparison page
// reads three tables and compares scores; everything the product generates
// about a person — evaluations, recruiter assessments, psychology, culture
// match, triangulation, risk reviews — is asset-shaped and joined to nothing.
// This module is the join: every asset is reduced to evidence items keyed to
// the five calibration dimensions, so a comparison can be about what is KNOWN
// rather than about a number.
//
// ── Two ideas do the work here ──
//
// 1. ABSENCE IS A FINDING. "We have no evidence of this candidate's regulatory
//    exposure" is usually more decision-relevant than any score, and it is
//    exactly what a scores-only comparison cannot express. A cell with no
//    evidence renders as a gap, never as a zero — those are different claims
//    and conflating them is how a candidate gets rejected for a silence.
//
// 2. PROVENANCE IS NOT INTERCHANGEABLE. A claim on a CV is the candidate's own
//    account; a recruiter assessment is a professional judgement; a score is
//    computed. Flattening them into one confidence number would let the
//    strongest-sounding CV beat the best-evidenced candidate. Every item
//    carries its basis, and coverage is computed from the STRONGEST basis
//    present rather than from a count of items.
//
// This module deliberately produces no composite score for a person. That is a
// settled product decision — the app reports evidence and coverage instead —
// and it is also the honest shape: the dimensions are weighted differently per
// role, and collapsing them hides the trade-off the recruiter is being paid to
// make.

import {
  DIMENSION_KEYS,
  type DimensionKey,
  type DimensionWeights,
} from "@/lib/ai/onboarding-analysis";

/**
 * Where a piece of evidence came from, strongest first.
 *
 * Order is load-bearing: `strongestBasis` picks by this ranking, and coverage
 * keys off it.
 */
export const EVIDENCE_BASES = [
  /** Computed by the app from structured inputs — the scoring engine. */
  "measured",
  /** A human recruiter's recorded judgement. */
  "recruiter",
  /** Generated by an agent from the candidate's material. */
  "ai_inferred",
  /** The candidate's own account — CV claims, self-description. */
  "self_reported",
] as const;

export type EvidenceBasis = (typeof EVIDENCE_BASES)[number];

const BASIS_RANK: Record<EvidenceBasis, number> = {
  measured: 0,
  recruiter: 1,
  ai_inferred: 2,
  self_reported: 3,
};

/** Whether an item supports the candidate on this dimension or cuts against. */
export type EvidencePolarity = "supports" | "contradicts" | "neutral";

export type EvidenceItem = {
  dimension: DimensionKey;
  basis: EvidenceBasis;
  polarity: EvidencePolarity;
  /** Human label for where this came from — "Recruiter assessment", "CV". */
  source_label: string;
  /** One line the recruiter can read without opening the source. */
  summary: string;
};

export type CoverageState =
  /** At least one non-self-reported item supporting or contradicting. */
  | "evidenced"
  /** Only the candidate's own account. Known, but not corroborated. */
  | "thin"
  /** Nothing at all. A gap, not a zero. */
  | "absent"
  /** Items disagree — the most interesting cell on the grid. */
  | "conflicted";

export type DimensionCoverage = {
  dimension: DimensionKey;
  /** From the role's calibration. Null when the role was never calibrated. */
  weight: number | null;
  state: CoverageState;
  items: EvidenceItem[];
  /** Strongest basis present, for sorting and for the cell's tone. */
  best_basis: EvidenceBasis | null;
};

export type CandidateEvidence = {
  candidate_id: string;
  full_name: string;
  dimensions: Record<DimensionKey, DimensionCoverage>;
  /**
   * Dimensions the role weights heavily where we know little or nothing. The
   * shortlist question in one field: not "who scored highest" but "what would
   * we still need to find out before putting this person in front of anyone".
   */
  critical_gaps: DimensionKey[];
};

/**
 * A dimension at or above this weight is one the role actually turns on.
 *
 * Weights are 1–10 from the calibration agent. Deliberately a named constant:
 * it decides which silences get escalated to `critical_gaps`, and it should be
 * revisited against real searches rather than defended as a magic number.
 */
export const HIGH_WEIGHT_THRESHOLD = 7;

export function strongestBasis(
  items: readonly EvidenceItem[]
): EvidenceBasis | null {
  let best: EvidenceBasis | null = null;
  for (const item of items) {
    if (best === null || BASIS_RANK[item.basis] < BASIS_RANK[best]) {
      best = item.basis;
    }
  }
  return best;
}

/**
 * Reduce a dimension's items to one state.
 *
 * `conflicted` outranks everything: when the material disagrees, that is the
 * finding, and burying it under "evidenced" would hide the one cell a recruiter
 * most needs to open.
 */
export function coverageState(items: readonly EvidenceItem[]): CoverageState {
  if (items.length === 0) return "absent";

  const supports = items.some((i) => i.polarity === "supports");
  const contradicts = items.some((i) => i.polarity === "contradicts");
  if (supports && contradicts) return "conflicted";

  const basis = strongestBasis(items);
  // Only the candidate's own account. We know what they say, which is not the
  // same as knowing the thing.
  if (basis === "self_reported") return "thin";

  return "evidenced";
}

export type BuildEvidenceInput = {
  candidate_id: string;
  full_name: string;
  items: readonly EvidenceItem[];
};

/**
 * Build one candidate's index.
 *
 * Every dimension is present in the output whether or not it has evidence —
 * a comparison grid with missing rows silently drops the gaps, which are the
 * point.
 */
export function buildCandidateEvidence(
  input: BuildEvidenceInput,
  weights: DimensionWeights | null
): CandidateEvidence {
  const dimensions = {} as Record<DimensionKey, DimensionCoverage>;
  const critical_gaps: DimensionKey[] = [];

  for (const dimension of DIMENSION_KEYS) {
    const items = input.items.filter((i) => i.dimension === dimension);
    const state = coverageState(items);
    const weight = weights ? (weights[dimension] ?? null) : null;

    dimensions[dimension] = {
      dimension,
      weight,
      state,
      items,
      best_basis: strongestBasis(items),
    };

    // A gap only matters against what the role needs. An absent `regulatory`
    // on a role that does not weight regulation is not a finding.
    if (
      weight !== null &&
      weight >= HIGH_WEIGHT_THRESHOLD &&
      (state === "absent" || state === "thin")
    ) {
      critical_gaps.push(dimension);
    }
  }

  return {
    candidate_id: input.candidate_id,
    full_name: input.full_name,
    dimensions,
    critical_gaps,
  };
}

// ---------------------------------------------------------------------------
// Comparison
// ---------------------------------------------------------------------------

export type DimensionComparison = {
  dimension: DimensionKey;
  weight: number | null;
  /** Per candidate, in the order supplied. */
  cells: Array<{ candidate_id: string; coverage: DimensionCoverage }>;
  /**
   * True when the candidates genuinely differ here — some evidenced, some not.
   * The rows worth reading first.
   */
  differentiating: boolean;
  /** Nobody has evidence. A gap in the SEARCH, not in any candidate. */
  blind_spot: boolean;
};

export type ComparisonGrid = {
  candidates: CandidateEvidence[];
  /** Heaviest-weighted dimensions first — the role's own priorities. */
  rows: DimensionComparison[];
};

/**
 * Build the side-by-side.
 *
 * Rows are ordered by the role's weights rather than alphabetically or by any
 * candidate's strength, so the grid reads in the order the role actually cares
 * about. Two derived flags carry most of the value:
 *
 *  - `differentiating` — the candidates actually differ here, so this row is
 *    where a decision gets made.
 *  - `blind_spot` — NOBODY has evidence. That is a finding about the process,
 *    not about the people, and it is invisible in a scores table because every
 *    candidate looks equally unproven.
 */
export function buildComparisonGrid(
  candidates: readonly CandidateEvidence[],
  weights: DimensionWeights | null
): ComparisonGrid {
  const rows: DimensionComparison[] = DIMENSION_KEYS.map((dimension) => {
    const cells = candidates.map((c) => ({
      candidate_id: c.candidate_id,
      coverage: c.dimensions[dimension],
    }));

    const known = cells.filter(
      (c) => c.coverage.state === "evidenced" || c.coverage.state === "conflicted"
    ).length;

    return {
      dimension,
      weight: weights ? (weights[dimension] ?? null) : null,
      cells,
      differentiating: known > 0 && known < cells.length,
      blind_spot: cells.length > 0 && known === 0,
    };
  });

  rows.sort((a, b) => (b.weight ?? 0) - (a.weight ?? 0));

  return { candidates: [...candidates], rows };
}

/** Dimensions no candidate has evidence on — what the search failed to test. */
export function blindSpots(grid: ComparisonGrid): DimensionKey[] {
  return grid.rows.filter((r) => r.blind_spot).map((r) => r.dimension);
}
