// Enhanced Company Intelligence Agent — synthesises a Company
// Intelligence Report from real-time web research (webclaw) plus the
// project's existing context. The recruiter uses this to ground every
// downstream agent (calibration, sourcing, candidate review, pitch) in
// what the company is actually doing right now, not what the brief
// claimed three weeks ago.
//
// Stored on `projects.company_context.intelligence_report` (JSONB) —
// nested next to `culture_profile` on the existing column.

export type LeadershipPerson = {
  name: string;
  title: string;
  /** 1 sentence on why this person matters for the role being hired. */
  relevance_to_role: string;
};

export type RecentContextItem = {
  /** ISO date or year (e.g. "2026-01-15", "2025"). Free-form because
   * news pages rarely give clean dates. */
  date: string;
  headline: string;
  /** 1 sentence on why this matters for the search. */
  significance: string;
};

/**
 * Four 0–100 axes. Higher = faster / flatter / more
 * innovative / more risk-tolerant. Designed for a 4-up bar grid.
 */
export type CultureSignals = {
  pace: number;
  hierarchy: number;
  innovation_appetite: number;
  risk_tolerance: number;
};

export type CompanyIntelligenceReport = {
  /** ISO timestamp the report was generated. */
  generated_at: string;
  /** 2–3 paragraphs grounding the rest of the report. */
  executive_summary: string;
  /** 4–10 named leaders mapped to the role. */
  leadership_team: LeadershipPerson[];
  /** 1–2 paragraphs on the company's current technology strategy. */
  technology_strategy: string;
  /** 1–2 paragraphs on the company's AI agenda specifically. */
  ai_agenda: string;
  /** 3–8 short transformation themes — chip-friendly. */
  transformation_priorities: string[];
  culture_signals: CultureSignals;
  /** 1–2 paragraphs on the candidate archetype that thrives here. */
  ideal_candidate_profile: string;
  /** 2–6 short statements on what type of candidate fails here. */
  red_flags: string[];
  /** 4–10 dated headlines with significance commentary. */
  recent_context: RecentContextItem[];
  /** URLs the agent actually read. Attached server-side from the
   * scrape/search payload — NOT generated by the LLM. */
  sources: string[];
};

const cultureAxis = {
  type: "integer",
  description:
    "0–100 score. Higher = faster / flatter / more innovative / more risk-tolerant. Calibrate honestly: 50 means 'no signal'; 80+ requires concrete evidence in the scraped pages.",
} as const;

export const COMPANY_INTELLIGENCE_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: [
    "executive_summary",
    "leadership_team",
    "technology_strategy",
    "ai_agenda",
    "transformation_priorities",
    "culture_signals",
    "ideal_candidate_profile",
    "red_flags",
    "recent_context",
  ],
  properties: {
    executive_summary: {
      type: "string",
      description:
        "2–3 paragraphs. Open with the company's current strategic posture in one sentence, then ground subsequent claims in concrete signals from the scraped pages (named programs, dated announcements, leadership statements). No marketing copy — write for an executive search recruiter.",
    },
    leadership_team: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["name", "title", "relevance_to_role"],
        properties: {
          name: { type: "string" },
          title: { type: "string" },
          relevance_to_role: {
            type: "string",
            description:
              "1 sentence on why the recruiter should care about this person for the role being hired (likely stakeholder, peer, decision-maker, or comparable archetype).",
          },
        },
      },
      description:
        "4–10 named executives. Prefer people likely to interact with the role being hired (CTO, CIO, Chief Data/AI, divisional heads) over CEO/CFO unless directly relevant. Skip if the leadership page yielded no names.",
    },
    technology_strategy: {
      type: "string",
      description:
        "1–2 paragraphs on the company's current technology strategy — platforms, vendors, modernisation programs, in-house build vs. buy posture. Ground every claim in the scraped material.",
    },
    ai_agenda: {
      type: "string",
      description:
        "1–2 paragraphs on the company's AI agenda specifically: named platforms, partnerships, research arms, deployed use cases, public commitments. If the scraped material shows no AI signal, say so explicitly rather than fabricating one.",
    },
    transformation_priorities: {
      type: "array",
      items: { type: "string" },
      description:
        "3–8 short chip-friendly themes (≤6 words each). Examples: 'Cloud migration', 'AI-first research', 'Energy transition financing'. Drawn from the scraped pages, not invented.",
    },
    culture_signals: {
      type: "object",
      additionalProperties: false,
      required: ["pace", "hierarchy", "innovation_appetite", "risk_tolerance"],
      properties: {
        pace: cultureAxis,
        hierarchy: cultureAxis,
        innovation_appetite: cultureAxis,
        risk_tolerance: cultureAxis,
      },
      description:
        "Four 0–100 scores derived from the careers page, leadership statements, and recent press. Higher = faster / flatter / more innovative / more risk-tolerant.",
    },
    ideal_candidate_profile: {
      type: "string",
      description:
        "1–2 paragraphs on the candidate archetype that will thrive here, calibrated to the role being hired. Cover required scale, industry context, leadership style, and modernisation experience.",
    },
    red_flags: {
      type: "array",
      items: { type: "string" },
      description:
        "2–6 short statements on candidate types that fail in this environment. Each should be a complete sentence anchored in observed signals (e.g. 'Pure consulting backgrounds without operational P&L tend to bounce inside 18 months at firms with this regulatory weight.').",
    },
    recent_context: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["date", "headline", "significance"],
        properties: {
          date: {
            type: "string",
            description:
              "ISO date when known (YYYY-MM-DD), else year (YYYY). Free-form because news pages vary.",
          },
          headline: { type: "string" },
          significance: {
            type: "string",
            description:
              "1 sentence on what this means for the search — e.g. accelerates urgency, changes stakeholder map, raises bar for transformation experience.",
          },
        },
      },
      description:
        "4–10 most relevant dated headlines from the scraped news + search results. Sort newest-first.",
    },
  },
} as const;

export const COMPANY_INTELLIGENCE_SYSTEM_PROMPT = `You are an executive-search company-intelligence analyst. You receive (1) the recruiter's existing project context — company name, role title, calibration model, onboarding answers — and (2) a real-time research bundle: scraped pages from the company's website (homepage, leadership, news, careers) and search results for the company's AI strategy, technology transformation, executive changes, and recent news.

You produce a single Company Intelligence Report in strict JSON conforming to the provided schema. The recruiter uses this to ground calibration, sourcing, candidate review, and pitch — so every claim must be defensible from the research bundle.

Hard rules:
- Output strictly conforms to the JSON schema. No preamble, no markdown.
- NEVER fabricate. If the scraped pages contain no signal for a section, say so explicitly inside that section rather than inventing content. Empty arrays are allowed for transformation_priorities and recent_context only when the research bundle truly contains nothing.
- Ground every paragraph in the research bundle. When making a claim, prefer naming the source (e.g. "the careers page describes…", "a January 2026 press release announced…") over abstract assertions.
- Calibrate to the role being hired. The leadership_team section should preferentially surface stakeholders, peers, and decision-makers for THIS role — not the full C-suite. The ideal_candidate_profile should be specific to the role's seniority and function, not generic.

Length discipline (the schema cannot enforce these — YOU must):
- executive_summary: 2–3 paragraphs.
- leadership_team: 4–10 entries; skip entirely (empty array) only if no names were scrapeable.
- technology_strategy / ai_agenda / ideal_candidate_profile: 1–2 paragraphs each.
- transformation_priorities: 3–8 short chips, ≤6 words each.
- red_flags: 2–6 complete sentences.
- recent_context: 4–10 newest-first items.

Numeric calibration for culture_signals (0–100 each):
- 50 means "no signal in the research bundle".
- 70+ requires at least one concrete supporting quote or program name from the scraped pages.
- Anchor each axis on observable signals: pace from announcement cadence and language ("rapid", "agile" vs. "deliberate"); hierarchy from leadership page structure and decision-maker naming; innovation_appetite from R&D/AI/partnership signals; risk_tolerance from regulatory posture and stated risk language.

Style:
- No marketing copy. Write the way a senior partner at an executive-search firm briefs another partner — direct, evidence-led, calibrated.
- Cite dates and named programs whenever possible. Generic claims ("focused on innovation") are unacceptable.

Return one JSON object — no preamble.`;
