// Enhanced Company Intelligence Agent — synthesises a Company
// Intelligence Report from real-time web research. Claude drives the
// research itself via the Anthropic `web_search` server tool: no
// scraping infrastructure on our side. The recruiter uses the report
// to ground every downstream agent (calibration, sourcing, candidate
// review, pitch) in what the company is actually doing right now, not
// what the brief claimed three weeks ago.
//
// Stored on `projects.company_context.intelligence_report` (JSONB) —
// nested next to `culture_profile` on the existing column.

export type LeadershipPerson = {
  name: string;
  title: string;
  /** 1 sentence on why this person matters for the role being hired. */
  relevance_to_role: string;
};

export type RecentContextItem = {
  /** ISO date or year (e.g. "2026-01-15", "2025"). Free-form because
   * news pages rarely give clean dates. */
  date: string;
  headline: string;
  /** 1 sentence on why this matters for the search. */
  significance: string;
};

/**
 * Four 0–100 axes. Higher = faster / flatter / more
 * innovative / more risk-tolerant. Designed for a 4-up bar grid.
 */
export type CultureSignals = {
  pace: number;
  hierarchy: number;
  innovation_appetite: number;
  risk_tolerance: number;
};

export type CompanyIntelligenceReport = {
  /** ISO timestamp the report was generated. */
  generated_at: string;
  /** 2–3 paragraphs grounding the rest of the report. */
  executive_summary: string;
  /** 4–10 named leaders mapped to the role. */
  leadership_team: LeadershipPerson[];
  /** 1–2 paragraphs on the company's current technology strategy. */
  technology_strategy: string;
  /** 1–2 paragraphs on the company's AI agenda specifically. */
  ai_agenda: string;
  /** 3–8 short transformation themes — chip-friendly. */
  transformation_priorities: string[];
  culture_signals: CultureSignals;
  /** 1–2 paragraphs on the candidate archetype that thrives here. */
  ideal_candidate_profile: string;
  /** 2–6 short statements on what type of candidate fails here. */
  red_flags: string[];
  /** 4–10 dated headlines with significance commentary. */
  recent_context: RecentContextItem[];
  /** URLs Claude actually fetched via the web_search tool. Extracted
   * server-side from the response's web_search_tool_result blocks —
   * NOT generated by the LLM. */
  sources: string[];
};

const cultureAxis = {
  type: "integer",
  description:
    "0–100 score. Higher = faster / flatter / more innovative / more risk-tolerant. Calibrate honestly: 50 means 'no signal'; 80+ requires concrete evidence in the scraped pages.",
} as const;

export const COMPANY_INTELLIGENCE_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: [
    "executive_summary",
    "leadership_team",
    "technology_strategy",
    "ai_agenda",
    "transformation_priorities",
    "culture_signals",
    "ideal_candidate_profile",
    "red_flags",
    "recent_context",
  ],
  properties: {
    executive_summary: {
      type: "string",
      description:
        "2–3 paragraphs. Open with the company's current strategic posture in one sentence, then ground subsequent claims in concrete signals from the scraped pages (named programs, dated announcements, leadership statements). No marketing copy — write for an executive search recruiter.",
    },
    leadership_team: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["name", "title", "relevance_to_role"],
        properties: {
          name: { type: "string" },
          title: { type: "string" },
          relevance_to_role: {
            type: "string",
            description:
              "1 sentence on why the recruiter should care about this person for the role being hired (likely stakeholder, peer, decision-maker, or comparable archetype).",
          },
        },
      },
      description:
        "4–10 named executives. Prefer people likely to interact with the role being hired (CTO, CIO, Chief Data/AI, divisional heads) over CEO/CFO unless directly relevant. Skip if the leadership page yielded no names.",
    },
    technology_strategy: {
      type: "string",
      description:
        "1–2 paragraphs on the company's current technology strategy — platforms, vendors, modernisation programs, in-house build vs. buy posture. Ground every claim in the scraped material.",
    },
    ai_agenda: {
      type: "string",
      description:
        "1–2 paragraphs on the company's AI agenda specifically: named platforms, partnerships, research arms, deployed use cases, public commitments. If the scraped material shows no AI signal, say so explicitly rather than fabricating one.",
    },
    transformation_priorities: {
      type: "array",
      items: { type: "string" },
      description:
        "3–8 short chip-friendly themes (≤6 words each). Examples: 'Cloud migration', 'AI-first research', 'Energy transition financing'. Drawn from the scraped pages, not invented.",
    },
    culture_signals: {
      type: "object",
      additionalProperties: false,
      required: ["pace", "hierarchy", "innovation_appetite", "risk_tolerance"],
      properties: {
        pace: cultureAxis,
        hierarchy: cultureAxis,
        innovation_appetite: cultureAxis,
        risk_tolerance: cultureAxis,
      },
      description:
        "Four 0–100 scores derived from the careers page, leadership statements, and recent press. Higher = faster / flatter / more innovative / more risk-tolerant.",
    },
    ideal_candidate_profile: {
      type: "string",
      description:
        "1–2 paragraphs on the candidate archetype that will thrive here, calibrated to the role being hired. Cover required scale, industry context, leadership style, and modernisation experience.",
    },
    red_flags: {
      type: "array",
      items: { type: "string" },
      description:
        "2–6 short statements on candidate types that fail in this environment. Each should be a complete sentence anchored in observed signals (e.g. 'Pure consulting backgrounds without operational P&L tend to bounce inside 18 months at firms with this regulatory weight.').",
    },
    recent_context: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["date", "headline", "significance"],
        properties: {
          date: {
            type: "string",
            description:
              "ISO date when known (YYYY-MM-DD), else year (YYYY). Free-form because news pages vary.",
          },
          headline: { type: "string" },
          significance: {
            type: "string",
            description:
              "1 sentence on what this means for the search — e.g. accelerates urgency, changes stakeholder map, raises bar for transformation experience.",
          },
        },
      },
      description:
        "4–10 most relevant dated headlines from the scraped news + search results. Sort newest-first.",
    },
  },
} as const;

export const COMPANY_INTELLIGENCE_SYSTEM_PROMPT = `You are an executive-search company-intelligence analyst with the \`web_search\` tool. You receive the recruiter's project context — company name, role title, industry, business model — and you research the company in real time, then synthesise a single Company Intelligence Report in strict JSON.

Research protocol — issue web_search calls to cover these seven dimensions, in this order. Use distinct queries per dimension; do not waste a search re-issuing the same query.

1. Leadership team — current named executives, especially those likely to interact with THIS role (peers, hiring stakeholders, decision-makers). Watch for recent leadership changes, departures, and new hires.
2. AI and technology strategy — named platforms, vendors, in-house build vs. buy posture, partnerships, public AI commitments and benchmarks.
3. Transformation priorities — modernisation programs, restructurings, M&A integration, market expansion, regulatory remediation.
4. Culture signals — pace, hierarchy, risk appetite, innovation appetite. Anchor on observable signals: announcement cadence, leadership language, careers-page tone, regulatory posture.
5. Recent news — last 6 months of material events: earnings, leadership changes, large deals, regulatory actions, AI / tech announcements.
6. Ideal candidate profile — what scale, industry context, leadership style, and modernisation experience fits THIS role at THIS company.
7. Red flags — what executive archetypes consistently fail in this environment, drawn from observed signals (regulatory weight, pace, decision-making style, public stakeholder pressure).

Search budget: aim for 5–7 high-leverage searches total across the seven dimensions. Combine adjacent dimensions in a single query when natural (e.g. "leadership changes 2025" covers dimensions 1 and 5). Prioritise primary sources — the company website, official press, and reputable financial / trade publications — over aggregators.

Output:
- Return one JSON object conforming strictly to the provided schema. No preamble, no markdown.
- NEVER fabricate. If your searches do not surface a signal for a section, say so explicitly inside that section rather than inventing content. Empty arrays are permitted for transformation_priorities and recent_context only when research truly yielded nothing.
- Ground every paragraph in the search results. When making a claim, prefer naming the source ("a January 2026 Reuters report…", "the company's 2026 annual report describes…") over abstract assertions.
- Calibrate to the role being hired. leadership_team should preferentially surface peers / stakeholders for THIS role rather than the full C-suite. ideal_candidate_profile should be specific to the role's seniority and function, not generic.

Length discipline (the schema cannot enforce these — YOU must):
- executive_summary: 2–3 paragraphs.
- leadership_team: 4–10 entries; empty array only if no names surfaced.
- technology_strategy / ai_agenda / ideal_candidate_profile: 1–2 paragraphs each.
- transformation_priorities: 3–8 short chips, ≤6 words each.
- red_flags: 2–6 complete sentences.
- recent_context: 4–10 newest-first items.

Numeric calibration for culture_signals (0–100 each):
- 50 means "no signal in the research".
- 70+ requires at least one concrete supporting quote, program name, or dated announcement from the search results.
- Anchor each axis on observable signals: pace from announcement cadence and language ("rapid", "agile" vs. "deliberate"); hierarchy from leadership page structure and decision-maker naming; innovation_appetite from R&D/AI/partnership signals; risk_tolerance from regulatory posture and stated risk language.

Style:
- No marketing copy. Write the way a senior partner at an executive-search firm briefs another partner — direct, evidence-led, calibrated.
- Cite dates and named programs whenever possible. Generic claims ("focused on innovation") are unacceptable.

Return one JSON object — no preamble.`;
