/**
 * Client contacts and client notes — see
 * `supabase/migrations/054_client_contacts_and_notes.sql`.
 *
 * The people we deal with at a client, and what was said. 049 built the
 * client as identity plus company profile and left both out; 050 took the
 * commercial half. This is the rest.
 *
 * ## Why the constants live here and not beside the actions
 *
 * A `"use server"` module may only export async functions. Exporting a
 * const from one makes every server action on the page it belongs to fail
 * at runtime — and only when one is invoked, so it ships. That is the bug
 * `outreach-actions.ts` shipped with (see §6 of the handoff). Everything a
 * client component needs to `.map` or `.includes` therefore lives in a
 * plain module like this one, exactly as `lib/fees/types.ts` does for the
 * fee panels.
 *
 * Nothing in this file is a security boundary. The vocabularies below
 * mirror CHECK constraints and the visibility tier mirrors an RLS policy;
 * Postgres is what enforces both.
 */

/** What this person is to us — not their job title, which is `title`. */
export const CONTACT_TYPES = [
  "hiring_manager",
  "hr",
  "executive",
  "procurement",
  "finance",
  "other",
] as const;

export type ContactType = (typeof CONTACT_TYPES)[number];

export const CONTACT_TYPE_LABELS: Record<ContactType, string> = {
  hiring_manager: "Hiring manager",
  hr: "HR / talent",
  executive: "Executive",
  procurement: "Procurement",
  finance: "Finance",
  other: "Other",
};

export type ClientContactRow = {
  id: string;
  organization_id: string;
  client_id: string;
  full_name: string;
  title: string | null;
  email: string | null;
  phone: string | null;
  linkedin_url: string | null;
  /** `nullif(btrim(lower(email)), '')`, generated by Postgres. The dedupe key. */
  email_key: string | null;
  contact_type: ContactType;
  is_primary: boolean;
  /**
   * People leave. Archiving keeps the row a portal token and a placement
   * sign-off can still point at, which deleting would sever.
   */
  is_archived: boolean;
  created_by: string | null;
  created_at: string;
  updated_at: string;
};

export const CLIENT_CONTACT_COLUMNS =
  "id, organization_id, client_id, full_name, title, email, phone, linkedin_url, email_key, contact_type, is_primary, is_archived, created_by, created_at, updated_at";

/**
 * The note vocabulary.
 *
 * `candidate_notes` from 020 minus `interview` — a client is not
 * interviewed — and with no `call_duration_minutes`, which exists on the
 * candidate side because screening calls are logged against a time budget
 * and means nothing for a client conversation.
 */
export const CLIENT_NOTE_TYPES = ["general", "call", "meeting", "email"] as const;
export type ClientNoteType = (typeof CLIENT_NOTE_TYPES)[number];

export const CLIENT_NOTE_TYPE_LABELS: Record<ClientNoteType, string> = {
  general: "Note",
  call: "Call",
  meeting: "Meeting",
  email: "Email",
};

/**
 * Who may read a note.
 *
 * `commercial` resolves to `fees:read` in RLS — the same predicate the fee
 * tables use, so "may see what we billed" stays one rule rather than two
 * that happen to agree today. See §10 of the handoff for why that line is
 * where it is.
 */
export const CLIENT_NOTE_VISIBILITIES = ["org", "commercial"] as const;
export type ClientNoteVisibility = (typeof CLIENT_NOTE_VISIBILITIES)[number];

export const CLIENT_NOTE_VISIBILITY_LABELS: Record<ClientNoteVisibility, string> = {
  org: "Everyone",
  commercial: "Commercial",
};

/**
 * What the composer says next to each tier.
 *
 * Worth spelling out in the UI rather than trusting the word alone: the
 * cost of picking the wrong one is a viewer reading the rate negotiation,
 * and "Commercial" on its own does not tell anybody that.
 */
export const CLIENT_NOTE_VISIBILITY_HINTS: Record<ClientNoteVisibility, string> = {
  org: "Any active member of the org can read this",
  commercial: "Only roles that can see fees and revenue",
};

export type ClientNoteRow = {
  id: string;
  organization_id: string;
  client_id: string;
  contact_id: string | null;
  created_by: string | null;
  /**
   * The author's name as it was when the note was written. `created_by` is
   * ON DELETE SET NULL, so without this every note a departed colleague
   * wrote goes anonymous the day their account is removed — the same fix
   * 053 made with `actor_label`. `candidate_notes` still has that gap.
   */
  author_label: string | null;
  note_type: ClientNoteType;
  content: string;
  visibility: ClientNoteVisibility;
  is_pinned: boolean;
  created_at: string;
  updated_at: string;
};

export const CLIENT_NOTE_COLUMNS =
  "id, organization_id, client_id, contact_id, created_by, author_label, note_type, content, visibility, is_pinned, created_at, updated_at";

/**
 * Narrow an untrusted value to a contact type.
 *
 * Same reasoning as `parseRole` and `parseActivityEventType`: the column is
 * `text` with a CHECK, and a value outside the vocabulary should lose
 * behaviour rather than gain it.
 */
export function parseContactType(value: unknown): ContactType | null {
  if (typeof value !== "string") return null;
  return (CONTACT_TYPES as readonly string[]).includes(value)
    ? (value as ContactType)
    : null;
}

export function parseClientNoteType(value: unknown): ClientNoteType | null {
  if (typeof value !== "string") return null;
  return (CLIENT_NOTE_TYPES as readonly string[]).includes(value)
    ? (value as ClientNoteType)
    : null;
}

export function parseClientNoteVisibility(value: unknown): ClientNoteVisibility | null {
  if (typeof value !== "string") return null;
  return (CLIENT_NOTE_VISIBILITIES as readonly string[]).includes(value)
    ? (value as ClientNoteVisibility)
    : null;
}

/**
 * The dedupe key, matching the generated column in Postgres.
 *
 * Kept in step with `client_contacts.email_key` the same way
 * `clientNameKey()` is kept in step with `clients.name_key`, and for the
 * same reason: the application needs to predict a collision before the
 * index reports one, so the user gets a sentence rather than a constraint
 * name. There is a test that says these two agree.
 */
export function contactEmailKey(email: string | null | undefined): string | null {
  const trimmed = (email ?? "").trim().toLowerCase();
  return trimmed === "" ? null : trimmed;
}

/**
 * How a contact should be labelled wherever one line is all there is —
 * a placement's sign-off, a portal token, an activity row.
 *
 * The title is included because "Jane Okafor" is not enough to tell two
 * people apart at a bank and "Jane Okafor // MD, Markets" is.
 */
export function contactLabel(
  contact: Pick<ClientContactRow, "full_name" | "title">
): string {
  const name = contact.full_name.trim();
  const title = contact.title?.trim();
  return title ? `${name} // ${title}` : name;
}

/**
 * Sort for the contact list: primary first, then archived last, then by
 * name.
 *
 * Done here rather than only in SQL because the archived filter is a client
 * toggle — re-querying to reorder a list bounded by how many people work in
 * one procurement department is a round trip for nothing.
 */
export function sortContacts(contacts: ClientContactRow[]): ClientContactRow[] {
  return [...contacts].sort((a, b) => {
    if (a.is_archived !== b.is_archived) return a.is_archived ? 1 : -1;
    if (a.is_primary !== b.is_primary) return a.is_primary ? -1 : 1;
    return a.full_name.localeCompare(b.full_name);
  });
}
