import type { CompanyContext } from "@/lib/ai/role-analysis";
import type { ClientPsychology } from "@/lib/ai/client-psychology-agent";

/**
 * The client entity — see `supabase/migrations/049_clients.sql`.
 *
 * A client is the company a mandate is run *for*. It existed only as
 * `projects.company_name`, a text column, until 049. Two mandates at the
 * same bank were unrelated rows that happened to share a string.
 *
 * ## The profile fields are not invented
 *
 * `industry` through `regulatory_environment` are the executive-search
 * intake, lifted from `executive_searches` where they were being captured
 * per search. They are all nullable text rather than enums: the intake has
 * always taken free text ("~$4bn", "4,000–6,000"), and narrowing that to a
 * vocabulary is a product decision nobody has made.
 */
export type ClientProfileFields = {
  industry: string | null;
  business_model: string | null;
  revenue_range: string | null;
  employee_count: string | null;
  funding_stage: string | null;
  ownership_structure: string | null;
  geographic_footprint: string | null;
  regulatory_environment: string | null;
};

export type ClientRow = ClientProfileFields & {
  id: string;
  organization_id: string;
  name: string;
  /** `lower(btrim(name))`, generated by Postgres. The dedupe key. */
  name_key: string;
  domain: string | null;
  /**
   * Canonical company research. Mandates snapshot this into their own
   * `company_context` at the moment they use it, so an exported report
   * keeps rendering what it was built from.
   */
  company_context: Partial<CompanyContext>;
  client_psychology: ClientPsychology | null;
  company_context_refreshed_at: string | null;
  client_psychology_refreshed_at: string | null;
  created_by: string | null;
  created_at: string;
  updated_at: string;
};

/** The columns a list screen needs. Kept in one place so the `select()` strings agree. */
export const CLIENT_LIST_COLUMNS =
  "id, name, domain, industry, business_model, geographic_footprint, company_context_refreshed_at, created_at, updated_at";

export const CLIENT_DETAIL_COLUMNS =
  "id, organization_id, name, name_key, domain, industry, business_model, revenue_range, employee_count, funding_stage, ownership_structure, geographic_footprint, regulatory_environment, company_context, client_psychology, company_context_refreshed_at, client_psychology_refreshed_at, created_by, created_at, updated_at";

/**
 * The profile fields in the order they should be shown, with their labels.
 *
 * One list rather than a hand-built table per screen: the client detail page
 * and the executive-search intake both render these, and they drifted apart
 * once already when the intake grew `ownership_structure`.
 */
export const CLIENT_PROFILE_FIELDS: ReadonlyArray<{
  key: keyof ClientProfileFields;
  label: string;
}> = [
  { key: "industry", label: "Industry" },
  { key: "business_model", label: "Business model" },
  { key: "revenue_range", label: "Revenue" },
  { key: "employee_count", label: "Headcount" },
  { key: "funding_stage", label: "Funding stage" },
  { key: "ownership_structure", label: "Ownership" },
  { key: "geographic_footprint", label: "Footprint" },
  { key: "regulatory_environment", label: "Regulatory" },
];

/**
 * The placeholder `projects/new/actions.ts` writes before the role-analysis
 * agent resolves the real company name.
 *
 * Duplicated in `resolve_client()` in 049, which is the enforcing copy — this
 * one lets the app avoid a pointless round trip. Both spellings are checked
 * because the source uses U+2026 but three dots survive some editors.
 */
const PLACEHOLDER_NAMES = new Set(["analyzing…", "analyzing..."]);

/**
 * Whether a company string names a real client.
 *
 * Returns false for the analysis placeholder and for blanks, which is the
 * difference between "this mandate has no client yet" and "this mandate's
 * client is called Analyzing…".
 */
export function isResolvableClientName(name: string | null | undefined): boolean {
  const trimmed = (name ?? "").trim();
  if (!trimmed) return false;
  return !PLACEHOLDER_NAMES.has(trimmed.toLowerCase());
}

/** The dedupe key, matching the generated column in Postgres. */
export function clientNameKey(name: string): string {
  return name.trim().toLowerCase();
}
