/**
 * Illustrative simulator runs.
 *
 * WHAT THESE ARE: hand-written examples of the SHAPE of a simulator
 * result. They are not model output, not captured from a real run, and
 * not verified against any company. Every surface that renders one must
 * say so — see `ILLUSTRATIVE_NOTICE` below and the banner in
 * live-simulator.tsx.
 *
 * WHY THEY EXIST: the simulator is the only proof a prospect can verify
 * for themselves, and it depends on a metered upstream API. When that
 * API is unavailable the page previously showed a single hardcoded
 * panel while telling the visitor it was "a worked example of the same
 * output" — which was not true of the brief they had just typed. These
 * fixtures make the fallback specific to what was asked, and make the
 * three example chips resolve instantly without touching the network.
 *
 * WHEN THE REAL PIPELINE IS AVAILABLE: regenerate these from it, keep
 * the same file shape, and change the notice to say the run was
 * captured rather than written. Do not quietly relabel hand-written
 * content as captured output — the entire point of this file is that
 * the page does not claim more than it can support.
 *
 * CONTENT RULES: describe the role, not the company. These name real
 * organisations only because the example briefs do; nothing here should
 * assert a checkable fact about any named company's internal state.
 */

export type DemoResult = {
  role_title: string;
  company_name: string;
  seniority: string;
  function: string;
  inferred_scope: string;
  missing_information: string[];
  calibration_weights: {
    technical: number;
    domain: number;
    leadership: number;
    regulatory: number;
    transformation: number;
  };
  boolean_queries: string[];
};

export type IllustrativeRun = {
  /** The brief this run illustrates. Matches a TYPING_EXAMPLES entry. */
  brief: string;
  result: DemoResult;
};

/** Shown wherever an illustrative run is rendered. Keep it blunt. */
export const ILLUSTRATIVE_NOTICE =
  "Written by us to show the shape of the output. Not generated by the model, and not a live run.";

export const ILLUSTRATIVE_RUNS: IllustrativeRun[] = [
  {
    brief: "Head of IT Operations for RBC Capital Markets",
    result: {
      role_title: "Head of IT Operations",
      company_name: "RBC Capital Markets",
      seniority: "Director / Executive Director",
      function: "Technology operations, service management",
      inferred_scope:
        "Owns run-the-bank technology for a capital markets division: platform availability across trading hours, incident and problem management, and the service relationship with front-office desks. The role sits between engineering delivery and the business, and is judged on stability during market hours rather than on feature throughput.",
      missing_information: [
        "Does this cover front-office trading platforms, or infrastructure only?",
        "Team size and split between employees and managed-service vendors",
        "Which regions are in scope — is this follow-the-sun or single-region?",
        "Is there an active platform migration the incoming leader inherits?",
        "Reporting line: divisional CIO, or group infrastructure?",
      ],
      calibration_weights: {
        technical: 7,
        domain: 9,
        leadership: 8,
        regulatory: 7,
        transformation: 5,
      },
      boolean_queries: [
        '("Head of IT Operations" OR "Director of Technology Operations" OR "Head of Production Support") AND ("capital markets" OR "investment bank" OR "trading") AND (ITIL OR "incident management" OR "problem management")',
        'site:linkedin.com/in ("IT operations" OR "production support") ("capital markets" OR "fixed income" OR "equities") ("vice president" OR director)',
        '("service management" OR "major incident") AND ("front office" OR "trading floor") AND NOT (recruiter OR "talent acquisition")',
      ],
    },
  },
  {
    brief: "Chief Risk Officer for a UK challenger bank",
    result: {
      role_title: "Chief Risk Officer",
      company_name: "UK challenger bank (unnamed in brief)",
      seniority: "Executive Committee, board-facing",
      function: "Risk, regulatory and compliance",
      inferred_scope:
        "Accountable for the risk framework across credit, operational and conduct risk, and is the named point of contact for the regulator. A UK challenger bank implies a Senior Manager Function under the SM&CR regime, so the appointment is subject to regulatory approval and the shortlist has to survive that scrutiny as well as the board's.",
      missing_information: [
        "Is this an SMF4 (Chief Risk) appointment requiring regulatory approval?",
        "Balance sheet size and whether the bank holds a full banking licence",
        "Is the risk function being built for the first time, or inherited?",
        "Current standing with the regulator — any live remediation?",
        "Does the role own compliance and financial crime, or risk only?",
      ],
      calibration_weights: {
        technical: 4,
        domain: 9,
        leadership: 8,
        regulatory: 10,
        transformation: 6,
      },
      boolean_queries: [
        '("Chief Risk Officer" OR "Director of Risk" OR "Head of Risk") AND (bank OR banking OR "financial services") AND ("SM&CR" OR SMF4 OR PRA OR FCA)',
        'site:linkedin.com/in "chief risk officer" (bank OR "building society" OR "challenger bank") ("United Kingdom" OR London)',
        '("credit risk" AND "operational risk" AND "conduct risk") AND ("executive committee" OR "board") AND NOT (insurance OR broker)',
      ],
    },
  },
  {
    brief: "VP of Engineering at a Series-C fintech",
    result: {
      role_title: "VP of Engineering",
      company_name: "Series-C fintech (unnamed in brief)",
      seniority: "VP, reports to CTO or CEO",
      function: "Engineering leadership",
      inferred_scope:
        "Runs an engineering organisation through the transition from a single team to multiple teams with their own roadmaps — typically 40 to 120 engineers at this funding stage. The hard part is usually organisational rather than technical: hiring, managing managers, and holding delivery predictable while the company's commitments to its investors get firmer.",
      missing_information: [
        "Current engineering headcount and the target over 12 months",
        "Does this role own platform and infrastructure, or product teams only?",
        "Is there an existing management layer, or is this the first?",
        "Regulated product? A lending or payments licence changes the profile",
        "Is the CTO a founder, and does that constrain the remit?",
      ],
      calibration_weights: {
        technical: 8,
        domain: 6,
        leadership: 9,
        regulatory: 4,
        transformation: 7,
      },
      boolean_queries: [
        '("VP Engineering" OR "Vice President of Engineering" OR "Head of Engineering") AND (fintech OR payments OR lending) AND ("Series B" OR "Series C" OR "scale-up")',
        'site:linkedin.com/in ("vp of engineering" OR "head of engineering") (fintech OR payments) ("managing managers" OR "engineering managers")',
        '("scaled the team" OR "grew engineering") AND (fintech OR "financial technology") AND NOT (agency OR consultancy)',
      ],
    },
  },
  {
    brief: "CTO for a US healthcare-payer modernisation",
    result: {
      role_title: "Chief Technology Officer",
      company_name: "US healthcare payer (unnamed in brief)",
      seniority: "C-suite, reports to CEO",
      function: "Technology strategy and modernisation",
      inferred_scope:
        "Leads replacement or re-platforming of core payer systems — claims adjudication, enrolment and member services — in an environment where downtime has regulatory and member-care consequences. Modernisation programmes of this kind are measured in years, so the appointment is as much about the ability to hold a multi-year plan through leadership change as about architecture.",
      missing_information: [
        "Which core systems are in scope, and is a platform already selected?",
        "Lines of business — commercial, Medicare Advantage, Medicaid?",
        "Member volume and claims throughput",
        "Is there an existing modernisation programme, and what is its status?",
        "Build, buy, or systems-integrator-led delivery model?",
        "Does the role own data and analytics alongside core platforms?",
      ],
      calibration_weights: {
        technical: 8,
        domain: 9,
        leadership: 9,
        regulatory: 8,
        transformation: 10,
      },
      boolean_queries: [
        '("Chief Technology Officer" OR CTO OR "Chief Information Officer") AND (payer OR "health plan" OR "managed care") AND (modernization OR "core systems" OR claims)',
        'site:linkedin.com/in (cto OR cio) ("health plan" OR payer OR "Medicare Advantage") (modernization OR transformation)',
        '("claims adjudication" OR "core administrative processing") AND (CTO OR CIO OR "SVP Technology") AND NOT (provider OR hospital OR "health system")',
      ],
    },
  },
];

/**
 * Picks the illustrative run closest to a free-text brief by counting
 * shared meaningful words. Deliberately simple — it only has to choose
 * between four options, and a wrong choice degrades to "a comparable
 * mandate", which the banner already says. Falls back to the first run.
 */
export function nearestRun(brief: string): IllustrativeRun {
  const STOP = new Set([
    "a", "an", "the", "for", "of", "at", "in", "to", "and", "or", "with",
    "on", "by", "from", "as",
  ]);
  const words = (s: string) =>
    new Set(
      s
        .toLowerCase()
        .split(/[^a-z0-9&]+/)
        .filter((w) => w.length > 2 && !STOP.has(w))
    );

  const target = words(brief);
  let best = ILLUSTRATIVE_RUNS[0];
  let bestScore = -1;

  for (const run of ILLUSTRATIVE_RUNS) {
    let score = 0;
    for (const w of words(run.brief)) if (target.has(w)) score++;
    if (score > bestScore) {
      bestScore = score;
      best = run;
    }
  }
  return best;
}
