-- Executive Hiring Intelligence — global seed data.
--
-- Global library rows (organization_id NULL): 24 evidence-based executive
-- competencies and 8 role templates. Tenants read these via the
-- exec_*_select policies; org-private rows can be added later without
-- touching this data.
--
-- Indicators are observable evidence only — no psychological labels, no
-- protected-characteristic proxies. ON CONFLICT DO NOTHING keeps the
-- migration re-runnable.

-- ---------------------------------------------------------------------------
-- Competency library
-- ---------------------------------------------------------------------------

INSERT INTO public.executive_competencies
  (key, name, category, definition, positive_indicators, negative_indicators)
VALUES
  -- Leadership
  ('executive_communication', 'Executive Communication', 'leadership',
   'Communicates strategy, trade-offs, and status crisply to executive and board audiences.',
   ARRAY['Has presented strategy or major decisions to an executive team or board with documented outcomes',
         'Translates specialist detail into business terms for non-specialist stakeholders'],
   ARRAY['Relies on jargon when pressed for specifics',
         'Cannot articulate the rationale behind past decisions in plain terms']),
  ('organizational_design', 'Organizational Design', 'leadership',
   'Designs and evolves organization structures matched to strategy, stage, and scale.',
   ARRAY['Has restructured an organization with a stated before/after rationale and measured outcomes',
         'Has designed team topologies for a specific growth phase and revisited them as scale changed'],
   ARRAY['Org changes made without stated rationale or follow-up measurement']),
  ('talent_magnetism', 'Talent Attraction & Development', 'leadership',
   'Attracts, develops, and retains senior talent; builds leadership benches.',
   ARRAY['Can name leaders they hired or developed who were later promoted',
         'Prior teams show low regretted attrition over multi-year periods'],
   ARRAY['Cannot name leaders they developed',
         'Pattern of senior-team churn following their arrival']),
  ('decision_quality', 'Decision Quality Under Uncertainty', 'leadership',
   'Makes evidence-weighted, timely decisions with incomplete information and owns reversals.',
   ARRAY['Can walk through two or three consequential decisions including the information available at the time',
         'Documents decision rationale and revisits decisions when evidence changes'],
   ARRAY['Post-hoc rationalization of outcomes',
         'Cannot describe the alternatives that were considered and rejected']),
  ('change_leadership', 'Change Leadership', 'leadership',
   'Leads organizations through significant change with measurable adoption.',
   ARRAY['Led a named change program with measurable adoption or outcome metrics',
         'Can describe resistance encountered and how it was addressed'],
   ARRAY['Change programs stalled or were abandoned without documented lessons']),
  ('cross_functional_influence', 'Cross-Functional Influence', 'leadership',
   'Wins alignment and commitment across peer functions without direct authority.',
   ARRAY['Shipped outcomes that required sustained commitment from peer functions',
         'Peer stakeholders from prior roles corroborate collaborative delivery'],
   ARRAY['Track record limited to outcomes within their own reporting line']),

  -- Functional
  ('technology_strategy', 'Technology Strategy', 'functional',
   'Sets multi-year technology direction explicitly tied to business outcomes.',
   ARRAY['Authored a technology strategy that named business outcomes and was funded',
         'Can explain build-vs-buy and platform decisions with their commercial context'],
   ARRAY['Technology choices described without reference to business constraints or outcomes']),
  ('engineering_excellence', 'Engineering Excellence', 'functional',
   'Operates high-performing engineering organizations with visible delivery, quality, and reliability practice.',
   ARRAY['Can cite the delivery, quality, or reliability measures their org tracked and how they moved',
         'Introduced engineering practices with before/after evidence'],
   ARRAY['No measurable definition of engineering health in prior roles']),
  ('product_strategy', 'Product Strategy', 'functional',
   'Makes portfolio and roadmap choices grounded in customer and market evidence.',
   ARRAY['Can trace a major roadmap bet to the customer or market evidence behind it',
         'Has killed or pivoted initiatives based on evidence, not sunk cost'],
   ARRAY['Roadmap described as a feature list without underlying strategic logic']),
  ('ai_strategy', 'AI Strategy & Governance', 'functional',
   'Evaluates, deploys, and governs AI capabilities responsibly and with business justification.',
   ARRAY['Deployed AI capabilities with stated success criteria and governance controls',
         'Can articulate where AI was deliberately not used and why'],
   ARRAY['Describes AI adoption in trend language without concrete use cases or controls']),
  ('data_governance', 'Data Governance', 'functional',
   'Establishes data quality, lineage, access, and privacy compliance at scale.',
   ARRAY['Implemented data governance that passed internal or external audit',
         'Can describe specific data-quality or privacy incidents and the systemic fixes'],
   ARRAY['Treats data governance as a documentation exercise without operational teeth']),
  ('financial_stewardship', 'Financial Stewardship', 'functional',
   'Owns budgets with demonstrated cost-value discipline and forecasting accuracy.',
   ARRAY['Managed budgets of comparable scale with documented variance discipline',
         'Can explain a significant cost decision including what was protected and why'],
   ARRAY['Cannot state the size or shape of budgets previously owned']),
  ('operational_excellence', 'Operational Excellence', 'functional',
   'Builds repeatable operating cadences, processes, and execution rigor.',
   ARRAY['Installed operating cadences (planning, review, escalation) that survived their tenure',
         'Can show a process they simplified with measured effect'],
   ARRAY['Operating model described only in terms of meetings held']),
  ('commercial_acumen', 'Commercial Acumen', 'functional',
   'Understands revenue mechanics and partners effectively with go-to-market functions.',
   ARRAY['Can explain the revenue model and unit economics of prior businesses accurately',
         'Shipped work with measurable commercial impact co-owned with sales or marketing'],
   ARRAY['Frames commercial topics as someone else''s responsibility']),

  -- Operating
  ('zero_to_one_building', 'Zero-to-One Building', 'operating',
   'Built functions, products, or platforms from scratch with limited resources.',
   ARRAY['Started a function or product from nothing and can name the first hires and first milestones',
         'Made explicit scrappiness trade-offs appropriate to the stage'],
   ARRAY['Experience limited to inheriting mature teams and systems']),
  ('scaling_systems', 'Scaling Through Growth', 'operating',
   'Scaled teams, systems, and processes through rapid growth inflections.',
   ARRAY['Operated through a documented headcount or volume inflection (e.g. 3x within two years)',
         'Can describe what broke during scaling and how it was re-architected'],
   ARRAY['Describes scaling only in terms of hiring numbers']),
  ('enterprise_operating_experience', 'Enterprise Operating Experience', 'operating',
   'Operates effectively within large-organization constraints: procurement, audit, matrixed stakeholders.',
   ARRAY['Delivered outcomes inside organizations with formal procurement, audit, and compliance gates',
         'Can name the governance forums they operated through'],
   ARRAY['Visible frustration with enterprise process substituting for a strategy to work within it']),
  ('pnl_ownership', 'P&L Ownership', 'operating',
   'Holds direct profit-and-loss accountability for a business or business unit.',
   ARRAY['Owned a P&L and can state its size, margin profile, and their levers',
         'Made resourcing decisions with explicit P&L consequences'],
   ARRAY['Claims P&L ownership that was actually budget administration']),
  ('transformation_delivery', 'Transformation Delivery', 'operating',
   'Delivers named multi-year transformation programs to completion.',
   ARRAY['Named transformation program delivered with published milestones and outcomes',
         'Can describe scope cuts and sequencing decisions made under pressure'],
   ARRAY['Transformation experience limited to strategy decks without delivery accountability']),
  ('m_and_a_integration', 'M&A and Integration', 'operating',
   'Contributes to diligence and delivers post-merger integration.',
   ARRAY['Played a named role in diligence or integration with attributable outcomes',
         'Can describe an integration decision that preserved or destroyed value'],
   ARRAY['M&A exposure limited to being at a company while a deal happened']),

  -- Governance
  ('board_engagement', 'Board Engagement', 'governance',
   'Prepares for, presents to, and builds working relationships with boards.',
   ARRAY['Regular board presenter with artifacts they authored',
         'Has managed a difficult board conversation and can describe the preparation'],
   ARRAY['Board exposure limited to attending as an observer']),
  ('regulatory_compliance', 'Regulatory Navigation', 'governance',
   'Operates in regulated environments and manages regulator relationships.',
   ARRAY['Operated under named regulatory regimes and can describe specific obligations they owned',
         'Managed an examination, remediation, or regulator interaction directly'],
   ARRAY['Treats regulation as an obstacle rather than an operating parameter']),
  ('risk_management', 'Risk Management', 'governance',
   'Identifies, quantifies, and mitigates enterprise and operational risk.',
   ARRAY['Built or operated a risk register with named mitigations and owners',
         'Can describe a risk they escalated early and what it cost or saved'],
   ARRAY['Risk framing is purely reactive — incidents first, controls after']),
  ('investor_relations', 'Investor & Owner Relations', 'governance',
   'Communicates credibly with investors, PE operators, and owners; manages expectations.',
   ARRAY['Presented operating results to investors or a PE operating partner',
         'Can describe a moment expectations had to be reset and how it was handled'],
   ARRAY['No direct exposure to owners or investors despite senior titles'])
ON CONFLICT DO NOTHING;

-- ---------------------------------------------------------------------------
-- Role templates
-- ---------------------------------------------------------------------------

INSERT INTO public.executive_role_templates
  (key, title, summary, role_family, intake_defaults, competency_weights)
VALUES
  ('cto_seed_saas', 'CTO — Seed-Stage SaaS',
   'Player-coach technical founder-adjacent leader: ships the product with a small team while laying just enough foundation to survive success.',
   'cto',
   '{"role_title": "Chief Technology Officer", "role_family": "cto", "industry": "Software / SaaS", "business_model": "B2B SaaS", "funding_stage": "Seed", "revenue_range": "$0-1M ARR", "employee_count": "5-25", "reporting_line": "CEO", "board_exposure": "Presents at board meetings when technology is on the agenda", "team_size": "2-10 engineers", "business_situation": "Pre-product-market-fit: speed of learning matters more than architectural purity.", "expected_90_day_outcomes": "Owns the codebase and delivery cadence; ships weekly; first key hire in motion.", "expected_first_year_outcomes": "Product velocity sustained through PMF search; team of 8-12 with a working hiring engine; no catastrophic technical debt.", "preferred_leadership_style": "Hands-on player-coach"}'::jsonb,
   '[{"competency_key": "zero_to_one_building", "weight": 90, "rationale": "The entire job is building from nothing with constrained resources."},
     {"competency_key": "engineering_excellence", "weight": 70, "rationale": "Enough rigor to move fast without breaking trust — not enterprise process."},
     {"competency_key": "technology_strategy", "weight": 65, "rationale": "Directional architecture bets matter, but strategy documents do not."},
     {"competency_key": "talent_magnetism", "weight": 75, "rationale": "First ten engineers determine the company ceiling."},
     {"competency_key": "decision_quality", "weight": 70, "rationale": "Weekly irreversible-feeling decisions with thin evidence."},
     {"competency_key": "financial_stewardship", "weight": 40, "rationale": "Budget is small; runway awareness suffices."}]'::jsonb),

  ('cto_growth_saas', 'CTO — Growth-Stage SaaS',
   'Scales the engineering organization and platform through rapid growth while keeping delivery credible to the board.',
   'cto',
   '{"role_title": "Chief Technology Officer", "role_family": "cto", "industry": "Software / SaaS", "business_model": "B2B SaaS", "funding_stage": "Series C+", "revenue_range": "$20-100M ARR", "employee_count": "200-1000", "reporting_line": "CEO", "board_exposure": "Standing board attendee; owns the technology section", "team_size": "60-250 engineers", "business_situation": "Post-PMF scaling: the systems and org that got here will not get to the next stage.", "expected_90_day_outcomes": "Credible read on org and platform health; leadership team assessed; scaling plan drafted.", "expected_first_year_outcomes": "Org redesigned for scale; delivery predictability restored; platform re-architecture funded and underway.", "preferred_leadership_style": "Org-builder who stays technically credible"}'::jsonb,
   '[{"competency_key": "scaling_systems", "weight": 90, "rationale": "The core mandate is surviving the growth inflection."},
     {"competency_key": "organizational_design", "weight": 80, "rationale": "Team topology is the primary scaling instrument."},
     {"competency_key": "engineering_excellence", "weight": 80, "rationale": "Predictable delivery at scale is the board-visible output."},
     {"competency_key": "technology_strategy", "weight": 70, "rationale": "Platform bets now determine cost structure at 5x scale."},
     {"competency_key": "talent_magnetism", "weight": 75, "rationale": "Must recruit a leadership bench, not just engineers."},
     {"competency_key": "board_engagement", "weight": 55, "rationale": "Regular board exposure; technology narrative must hold up."}]'::jsonb),

  ('cio_financial_institution', 'CIO — Mid-Sized Financial Institution',
   'Modernizes technology inside a regulated institution while keeping regulators, auditors, and the board confident.',
   'cio',
   '{"role_title": "Chief Information Officer", "role_family": "cio", "industry": "Financial Services", "business_model": "Regulated financial institution", "ownership_structure": "Public or mutual", "employee_count": "1000-10000", "regulatory_environment": "Prudential and conduct regulation; regular examinations", "reporting_line": "CEO or COO", "board_exposure": "Quarterly board and risk-committee reporting", "team_size": "150-600 technology staff", "business_situation": "Legacy modernization under regulatory scrutiny with an inflexible change budget.", "expected_90_day_outcomes": "Regulatory posture assessed; critical-system risk map produced; quick credibility wins identified.", "expected_first_year_outcomes": "Modernization roadmap approved by the board; audit findings trending down; delivery credibility with business lines restored.", "preferred_leadership_style": "Steady, governance-fluent, evidence-led"}'::jsonb,
   '[{"competency_key": "regulatory_compliance", "weight": 90, "rationale": "Regulatory standing is existential for the institution."},
     {"competency_key": "enterprise_operating_experience", "weight": 85, "rationale": "Must deliver through procurement, audit, and committee structures."},
     {"competency_key": "risk_management", "weight": 80, "rationale": "Technology risk is board-level risk here."},
     {"competency_key": "transformation_delivery", "weight": 75, "rationale": "Legacy modernization is the multi-year mandate."},
     {"competency_key": "technology_strategy", "weight": 70, "rationale": "Strategy must reconcile modernization with regulatory constraint."},
     {"competency_key": "board_engagement", "weight": 70, "rationale": "Quarterly board and risk-committee accountability."}]'::jsonb),

  ('cpo_growth_tech', 'CPO — Growth-Stage Technology Company',
   'Turns a founder-led product instinct into a durable product organization and evidence-driven portfolio strategy.',
   'cpo',
   '{"role_title": "Chief Product Officer", "role_family": "cpo", "industry": "Technology", "business_model": "SaaS or platform", "funding_stage": "Series B-D", "employee_count": "100-800", "reporting_line": "CEO", "board_exposure": "Presents product strategy to the board", "team_size": "15-80 product managers and designers", "business_situation": "Founder is stepping back from day-to-day product; portfolio decisions now exceed one person''s intuition.", "expected_90_day_outcomes": "Product org assessed; decision rights clarified with the founder; portfolio evidence base started.", "expected_first_year_outcomes": "Roadmap governed by evidence; product org retained and upgraded; at least one major bet validated or killed on the evidence.", "preferred_leadership_style": "Evidence-led, founder-compatible"}'::jsonb,
   '[{"competency_key": "product_strategy", "weight": 90, "rationale": "Portfolio choices are the core of the mandate."},
     {"competency_key": "cross_functional_influence", "weight": 80, "rationale": "Product outcomes require engineering and GTM commitment."},
     {"competency_key": "commercial_acumen", "weight": 75, "rationale": "Roadmap must connect to revenue mechanics."},
     {"competency_key": "scaling_systems", "weight": 70, "rationale": "Product org and process must scale with the company."},
     {"competency_key": "decision_quality", "weight": 70, "rationale": "Kill/pivot decisions define the tenure."},
     {"competency_key": "talent_magnetism", "weight": 65, "rationale": "Senior PM talent follows credible product leaders."}]'::jsonb),

  ('vp_engineering_series_b', 'VP Engineering — Series B',
   'Installs delivery predictability and a hiring engine while the founding CTO focuses on architecture and vision.',
   'vp_engineering',
   '{"role_title": "VP Engineering", "role_family": "vp_engineering", "industry": "Technology", "business_model": "SaaS", "funding_stage": "Series B", "employee_count": "50-200", "reporting_line": "CTO or CEO", "board_exposure": "Occasional; delivery metrics feed board reporting", "team_size": "20-60 engineers", "business_situation": "Post-Series-B scaling: delivery is slipping as headcount doubles.", "expected_90_day_outcomes": "Delivery cadence measured and stabilized; management layer assessed; hiring pipeline running.", "expected_first_year_outcomes": "Team roughly doubled without velocity collapse; management bench installed; predictable quarterly delivery.", "preferred_leadership_style": "Operational, people-first, metrics-literate"}'::jsonb,
   '[{"competency_key": "scaling_systems", "weight": 85, "rationale": "Doubling the team without breaking delivery is the job."},
     {"competency_key": "engineering_excellence", "weight": 85, "rationale": "Delivery predictability is the visible mandate."},
     {"competency_key": "organizational_design", "weight": 75, "rationale": "Management structure must be built, not inherited."},
     {"competency_key": "talent_magnetism", "weight": 75, "rationale": "Owns the hiring engine end to end."},
     {"competency_key": "operational_excellence", "weight": 65, "rationale": "Cadences and process rigor carry the scaling."},
     {"competency_key": "cross_functional_influence", "weight": 60, "rationale": "Partnership with product determines throughput."}]'::jsonb),

  ('coo_scaling_startup', 'COO — Operationally Scaling Startup',
   'Builds the operating machine — cadences, processes, and accountability — under a founder-CEO whose strengths lie elsewhere.',
   'coo',
   '{"role_title": "Chief Operating Officer", "role_family": "coo", "industry": "Technology or tech-enabled services", "funding_stage": "Series B-D", "employee_count": "100-600", "reporting_line": "CEO", "board_exposure": "Standing board attendee for operating review", "budget_scope": "Owns operating budget across functions", "business_situation": "Growth has outrun the operating model; the CEO needs a partner who makes the machine run.", "expected_90_day_outcomes": "Operating cadence installed; cross-functional accountability visible; top three operational fires owned.", "expected_first_year_outcomes": "Predictable operating rhythm; measurable efficiency gains; leadership team operating as a system.", "preferred_leadership_style": "Systematic, calm, high-accountability"}'::jsonb,
   '[{"competency_key": "operational_excellence", "weight": 90, "rationale": "The operating machine is the deliverable."},
     {"competency_key": "scaling_systems", "weight": 85, "rationale": "Every process must survive the next doubling."},
     {"competency_key": "organizational_design", "weight": 80, "rationale": "Accountability structure is the primary tool."},
     {"competency_key": "financial_stewardship", "weight": 75, "rationale": "Owns the operating budget and efficiency narrative."},
     {"competency_key": "pnl_ownership", "weight": 70, "rationale": "Operating decisions carry direct P&L consequence."},
     {"competency_key": "cross_functional_influence", "weight": 70, "rationale": "Runs the seams between every function."}]'::jsonb),

  ('chief_ai_officer_regulated', 'Chief AI Officer — Regulated Enterprise',
   'Builds AI capability and governance simultaneously inside an enterprise where a single ungoverned deployment can trigger regulatory consequences.',
   'chief_ai_officer',
   '{"role_title": "Chief AI Officer", "role_family": "chief_ai_officer", "industry": "Regulated enterprise (financial services, healthcare, energy)", "employee_count": "5000+", "regulatory_environment": "Sector regulation plus emerging AI-specific regulation", "reporting_line": "CEO, CIO, or Chief Data Officer", "board_exposure": "Board and risk-committee reporting on AI posture", "business_situation": "Board-level pressure to capture AI value; equal pressure to avoid regulatory or reputational failure.", "expected_90_day_outcomes": "AI inventory and risk posture established; governance framework drafted; two or three high-value, low-risk use cases in flight.", "expected_first_year_outcomes": "Governed AI platform serving multiple business lines; measurable value delivered; regulator-ready documentation standing.", "preferred_leadership_style": "Credible with both engineers and regulators"}'::jsonb,
   '[{"competency_key": "ai_strategy", "weight": 90, "rationale": "The mandate is AI value with governance, not experimentation."},
     {"competency_key": "regulatory_compliance", "weight": 85, "rationale": "AI deployments must survive regulatory scrutiny."},
     {"competency_key": "data_governance", "weight": 80, "rationale": "AI quality is bounded by data governance maturity."},
     {"competency_key": "risk_management", "weight": 75, "rationale": "Every model is an operating risk to be owned."},
     {"competency_key": "executive_communication", "weight": 70, "rationale": "Must translate AI posture for board and regulators."},
     {"competency_key": "change_leadership", "weight": 70, "rationale": "Adoption across business lines is a change program."}]'::jsonb),

  ('head_of_transformation_fi', 'Head of Transformation — Financial Institution',
   'Owns a named multi-year transformation program end to end: sequencing, delivery, stakeholder management, and the scars to prove it.',
   'transformation',
   '{"role_title": "Head of Transformation", "role_family": "transformation", "industry": "Financial Services", "employee_count": "1000-20000", "regulatory_environment": "Prudential regulation; transformation may be remediation-driven", "reporting_line": "CEO or COO", "board_exposure": "Program status reported to board and possibly regulator", "budget_scope": "Multi-year program budget", "business_situation": "A named transformation program with executive sponsorship, hard deadlines, and organizational resistance.", "expected_90_day_outcomes": "Program re-baselined honestly; governance reset; critical-path risks surfaced to sponsors.", "expected_first_year_outcomes": "Milestones delivered against the re-baselined plan; stakeholder confidence measurably recovered; benefits tracking live.", "preferred_leadership_style": "Delivery-obsessed, politically fluent, honest under pressure"}'::jsonb,
   '[{"competency_key": "transformation_delivery", "weight": 90, "rationale": "Delivery accountability is the entire role."},
     {"competency_key": "change_leadership", "weight": 85, "rationale": "The program fails without adoption."},
     {"competency_key": "enterprise_operating_experience", "weight": 80, "rationale": "Must deliver through committees, audit, and procurement."},
     {"competency_key": "cross_functional_influence", "weight": 80, "rationale": "Owns outcomes delivered by other people''s teams."},
     {"competency_key": "regulatory_compliance", "weight": 70, "rationale": "Remediation-driven programs answer to regulators."},
     {"competency_key": "executive_communication", "weight": 70, "rationale": "Honest status reporting sustains sponsorship."}]'::jsonb)
ON CONFLICT DO NOTHING;
